from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(500, 300)
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(12)
        Login.setFont(font)
        Login.setStyleSheet("background-color: rgb(24, 46, 17);")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Login)
        self.buttonBox.setGeometry(QtCore.QRect(340, 380, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.logoBadge = QtWidgets.QLabel(parent=Login)
        self.logoBadge.setGeometry(QtCore.QRect(70, 40, 61, 51))
        self.logoBadge.setStyleSheet("image: url(../Resources/logo.png);")
        self.logoBadge.setText("")
        self.logoBadge.setObjectName("logoBadge")
        self.namingLabel = QtWidgets.QLabel(parent=Login)
        self.namingLabel.setGeometry(QtCore.QRect(140, 40, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.namingLabel.setFont(font)
        self.namingLabel.setObjectName("namingLabel")
        self.loginTextEdit = QtWidgets.QLineEdit(parent=Login)
        self.loginTextEdit.setGeometry(QtCore.QRect(100, 130, 300, 41))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.loginTextEdit.setFont(font)
        self.loginTextEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.loginTextEdit.setStyleSheet("background-color: rgb(43, 54, 44);")
        self.loginTextEdit.setText("")
        self.loginTextEdit.setFrame(True)
        self.loginTextEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.loginTextEdit.setDragEnabled(False)
        self.loginTextEdit.setClearButtonEnabled(True)
        self.loginTextEdit.setObjectName("loginTextEdit")
        self.passwordTextEdit = QtWidgets.QLineEdit(parent=Login)
        self.passwordTextEdit.setGeometry(QtCore.QRect(100, 180, 300, 41))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.passwordTextEdit.setFont(font)
        self.passwordTextEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.passwordTextEdit.setStyleSheet("background-color: rgb(43, 54, 44);")
        self.passwordTextEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordTextEdit.setClearButtonEnabled(True)
        self.passwordTextEdit.setObjectName("passwordTextEdit")
        self.loginButton = QtWidgets.QPushButton(parent=Login)
        self.loginButton.setGeometry(QtCore.QRect(100, 230, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(24)
        font.setBold(True)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("background-color: rgb(51, 104, 36);")
        self.loginButton.setDefault(True)
        self.loginButton.setObjectName("loginButton")
        self.signupButton = QtWidgets.QPushButton(parent=Login)
        self.signupButton.setGeometry(QtCore.QRect(260, 230, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.signupButton.setFont(font)
        self.signupButton.setStyleSheet("background-color: rgb(36, 74, 27);")
        self.signupButton.setAutoDefault(True)
        self.signupButton.setDefault(False)
        self.signupButton.setFlat(False)
        self.signupButton.setObjectName("signupButton")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login Menu"))
        self.namingLabel.setText(_translate("Login", "Let\'s recycle"))
        self.loginTextEdit.setPlaceholderText(_translate("Login", "email"))
        self.passwordTextEdit.setPlaceholderText(_translate("Login", "password"))
        self.loginButton.setText(_translate("Login", "Login"))
        self.signupButton.setText(_translate("Login", "Sign up"))
